### ISSUE TITLE
Reusing the design for a local page

### ISSUE THREAD

**Issue by nvitucci** [okfn/opendataday#142]
Is it possible to reuse and customize the design of the homepage for a local event? If yes, do I need to add any license information?

**Comment by danfowler** [comment]
@nvitucci that's fine, however, we would like to support having individual event pages.  Have you seen these issues?   

https://github.com/okfn/opendataday/issues/101

https://github.com/okfn/opendataday/issues/129

Do you think you could fit your event info into such a template?  Otherwise, have you considered [writing an Italian translation](https://github.com/okfn/opendataday#translations) for the site?

I added an issue for your licensing question: https://github.com/okfn/opendataday/issues/143

cc: @morchickit

**Comment by nvitucci** [comment]
@danfowler Yes, I've seen the first issue (but not the second, thanks for mentioning it); anyway, I'd like to customize and remix the sections for a full webpage rather than just listing a specific event.

I am not working on an Italian webpage, but I'll be happy to contribute with an Italian translation.

**Comment by boamaod** [comment]
I see that now CC0 license is [explicitly specified](https://github.com/okfn/opendataday/commit/2d8d2ffd1fa5c0203e8489beca46f69015bd1e68#diff-dc5cde275269b574b34b1204b9221cb2). I am planning to build a data-related hackathon site on the design, so that's helpful, thanks.

**Comment by tlacoyodefrijol** [comment]
@nvitucci is the issue here done? Were you able to reuse the design?

**Comment by nvitucci** [comment]
Yes, I think this can be closed.

**Comment by tlacoyodefrijol** [comment]
Closing issue
