### ISSUE TITLE
Closing date for mini grant scheme is different in EN and FR version

### ISSUE THREAD

**Issue by pyrog** [okfn/opendataday#288]
* Apply to the mini-grant scheme by midday GMT on Friday 5th February 2021.
* Attention à l'appel à candidatures qui devrait être lancé en janvier 2020.

It seem that there is no closing date in other languages.

**Comment by StephenAbbott** [comment]
Thanks @pyrog for pointing out these issues. This is because the French translation of the opendataday.org website hasn't yet been updated by a Francophone speaker to reflect 2021 dates.

Are you able to help with this? Here is the fr translation file if you can update and submit a PR: https://github.com/okfn/opendataday/blob/master/content/contents%2Bfr.lr

**Comment by pyrog** [comment]
> Are you able to help with this? Here is the fr translation file if you can update and submit a PR:

Yes. See #290


So I use "Friday 5th February 2021" or I don't add date like other languages ?
